# Generated by Django 3.2.6 on 2021-09-01 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landmark', '0002_auto_20210901_1416'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FileUpload',
            new_name='imageModel',
        ),
    ]
